#开发环境配置
web:
  upload-path: /myfile/upload/
  #front-path: d:/myfile/front/
server:
  #\u7AEF\u53E3
  port: 8080
  context-path: /supervisions_backstage
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.supervisions: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    cache: false

  redis:
    # Redis服务器地址(localhost)
    host: localhost
    # Redis服务器地址(docker)
    #host: redis
    # Redis服务器连接密码（默认为空）
    password: 123456
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0 redis有16个库）
    database: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0

  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
  devtools:
    restart:
      enabled: true
  resources:
    #static-locations: file:${web.upload-path},file:${web.front-path}
    static-locations: classpath:/static/,file:${web.upload-path}
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.supervisions.modules
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
  session:
    # Session超时时间（默认30分钟）
    expireTime: 10080
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 1440